### ISSUE TITLE
Key Pair Not Documented, Creates ROLLBACK ISSUE

### ISSUE THREAD

**Issue by darkn3rd** [aws-samples/elasticache-refarch-chatapp#4]
### DESCRIPTION: In the chatapp.yml, there's a requirements for a EC2 KeyPair to be created.  This is not documented anywhere.  In the `chatapp.yaml`, on line 27, snippet here:

```yaml
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
```

### STEPS

1. Click on the `[Launch Stack]` button that refers to: 
    * https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=chatapp&templateURL=https://s3.amazonaws.com/elasticache-refarch-chatapp/chatapp.yaml
1. Navigate through the deafults 

### ACTUAL RESULTS

ROLLBACK as required parameter to meet constraint is not there.

### EXPECTED RESULTS

I would click on the button, run through the instructions and it would work.  There's no documentation on this requirement, other than the CFN template code.
